export const prospectPipelineBaseline = [
  {
    "id": "pr-0001",
    "seqNo": 1,
    "salesOfficer": "MM",
    "companyName": "Gaza G",
    "country": "Denmark",
    "followUpDuration": "",
    "estTeus": 1,
    "estTurnover": 2,
    "conversionRate": 0.4,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "Customer did trials for coco trays & said at the moment they are not looking to convert from the plastic materials they use. But in future they might consider, CONTACTED AGAIN AND ASKED INFORMATION FOR CURRENT PRODUCT RANGE"
  },
  {
    "id": "pr-0002",
    "seqNo": 2,
    "salesOfficer": "MM",
    "companyName": "St Aubin",
    "country": "Canada",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.6,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Quoted competitive prices to convert the customer from competition. They have already given this years order to competition and agreed to gove us the order for next year. 2026 July prices offered currently under discussions;"
  },
  {
    "id": "pr-0003",
    "seqNo": 3,
    "salesOfficer": "MM",
    "companyName": "Linax",
    "country": "Malaysia",
    "followUpDuration": "",
    "estTeus": 1,
    "estTurnover": 3,
    "conversionRate": 0.65,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": false,
    "sampleDelivered": true,
    "status": "Shoe sole buyer , connected, currenly working on sample development for customer original sample, Need to send samples to them. samples sent on 25th july and currently follwing up with Marchell -Buyer"
  },
  {
    "id": "pr-0004",
    "seqNo": 4,
    "salesOfficer": "MM",
    "companyName": "Artigian",
    "country": "Italy",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "connected via linkedin send calalog, asked for samples, need to arrange  said price is out , but need to work on closely"
  },
  {
    "id": "pr-0005",
    "seqNo": 5,
    "salesOfficer": "MM",
    "companyName": "Frog",
    "country": "United Kingdom",
    "followUpDuration": "",
    "estTeus": 2,
    "estTurnover": 6,
    "conversionRate": 0.8,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "Gully guard, Boi pipe done, bio pipe tested and sent to customer for review, Gully guard contruction done samples sent, need to do onsite test inside water. De watering bag yet to pass trials . customer said he will place po by sep"
  },
  {
    "id": "pr-0006",
    "seqNo": 6,
    "salesOfficer": "PD",
    "companyName": "Mattress Prod",
    "country": "Turkey",
    "followUpDuration": "",
    "estTeus": 2,
    "estTurnover": 6,
    "conversionRate": 0.8,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "Samples sent for testing MVSS 302 standard (testing by TOYO) and awaiting results. Prices to be submitted, trial order done"
  },
  {
    "id": "pr-0007",
    "seqNo": 7,
    "salesOfficer": "DP",
    "companyName": "PRB",
    "country": "Canada",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2.5,
    "conversionRate": 0.5,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "Sampels sent prices sent customer doing trials and review with competitor samples . we sent all 4 quality liners for the review"
  },
  {
    "id": "pr-0008",
    "seqNo": 8,
    "salesOfficer": "DP",
    "companyName": "DXB BEDDING",
    "country": "UAE",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2.5,
    "conversionRate": 0.3,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Prices offered. GOLS samples dispatched"
  },
  {
    "id": "pr-0009",
    "seqNo": 9,
    "salesOfficer": "MM",
    "companyName": "Iwan procircular",
    "country": "Netherlands",
    "followUpDuration": "",
    "estTeus": 8,
    "estTurnover": 6,
    "conversionRate": 0.5,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "working on block plank development, need 600kg holding capacity with coir and sustanable contenct"
  },
  {
    "id": "pr-0010",
    "seqNo": 10,
    "salesOfficer": "MM",
    "companyName": "Bleee Ne",
    "country": "Netherlands",
    "followUpDuration": "",
    "estTeus": 4,
    "estTurnover": 5,
    "conversionRate": 0.4,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "Price offers done samples done customer isdoing trials"
  },
  {
    "id": "pr-0011",
    "seqNo": 11,
    "salesOfficer": "MM",
    "companyName": "Adj india-",
    "country": "India",
    "followUpDuration": "",
    "estTeus": 6.75,
    "estTurnover": 4,
    "conversionRate": 0.4,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "price pending and sample ready"
  },
  {
    "id": "pr-0012",
    "seqNo": 12,
    "salesOfficer": "HR",
    "companyName": "Samar trading planter mat-New ref exiting customer",
    "country": "Italy",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.6,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "Samples price done customer need to do trials so keep following up"
  },
  {
    "id": "pr-0013",
    "seqNo": 13,
    "salesOfficer": "MM",
    "companyName": "Primehort -New ref exiting customer",
    "country": "New Zealand",
    "followUpDuration": "",
    "estTeus": 6.75,
    "estTurnover": 4,
    "conversionRate": 0.4,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "Price samples sent customer ok for prie and sample is ok ,currently in talks"
  },
  {
    "id": "pr-0014",
    "seqNo": 14,
    "salesOfficer": "MM",
    "companyName": "Ayogi",
    "country": "Japan",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.6,
    "expectedClosingTimeline": "0-6 Months",
    "priority": "HIGH",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Working on the samples, quotation sent inquiry from rileys"
  },
  {
    "id": "pr-0015",
    "seqNo": 15,
    "salesOfficer": "MM",
    "companyName": "Bellaflo",
    "country": "Austria",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.4,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": false,
    "sampleDelivered": true,
    "status": "Requested for waterproof pot and tray samples. They are currently buying from competition."
  },
  {
    "id": "pr-0016",
    "seqNo": 16,
    "salesOfficer": "MM",
    "companyName": "Brunn",
    "country": "Australia",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2.2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "called and got purchasing direct email and sent email to steve and eliska. Steve replied, need to follwup, prices offered with our product list"
  },
  {
    "id": "pr-0017",
    "seqNo": 17,
    "salesOfficer": "MM",
    "companyName": "Ace H",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 15,
    "estTurnover": 15,
    "conversionRate": 0.4,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Emailed send, first time called not successful,  second time called and asked to send vender request, need to register in the system, connected with soucing head, thomson and sent catelogue and vender regisration link Got the inquiry for Rayan for basket liners, need to work on prices , price is out with china prices, still unable to get target prices"
  },
  {
    "id": "pr-0018",
    "seqNo": 18,
    "salesOfficer": "MM",
    "companyName": "World Source Par",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 15,
    "estTurnover": 15,
    "conversionRate": 0.4,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "mike marlon .mmallon@worldsourcepartners.com,+1 609-610-8680,+1 860-290-8890 ext 205,+1 856-382-0073eric (609) 257-8900 called mik 18002889627  224, sent emails and he said he will reply.they will come back to us in september , sent the inquiry for ppt of full new innovative item list"
  },
  {
    "id": "pr-0019",
    "seqNo": 19,
    "salesOfficer": "MM",
    "companyName": "Geo Mat",
    "country": "Czech Republic",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 3,
    "conversionRate": 0.4,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "offered price for 50x 150 cm with carton packing like last time  but now customer requested dimension and pricing  is different In that case we can offer at  $1.3 /sqm  DAP for 2 x20m  target price is 1.133 which is below the margin "
  },
  {
    "id": "pr-0020",
    "seqNo": 20,
    "salesOfficer": "MM",
    "companyName": "Sunrise Hardware",
    "country": "Australia",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 3,
    "conversionRate": 0.4,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "wrote, brett connected, they have supplier for these but they are happy to explore our products. send offers on 22nd may"
  },
  {
    "id": "pr-0021",
    "seqNo": 21,
    "salesOfficer": "MM",
    "companyName": "Hortic",
    "country": "New Zealand",
    "followUpDuration": "",
    "estTeus": 10,
    "estTurnover": 10,
    "conversionRate": 0.5,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "Connected with soucing team, said that they will definetely get back once requirment arises , said prices are ok and working on with other suppliers"
  },
  {
    "id": "pr-0022",
    "seqNo": 22,
    "salesOfficer": "MM",
    "companyName": "Eco Sal",
    "country": "Portugal",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.6,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "Quotation submitted. Samples submtted(May 2026). Awaiting resposne. reminder emails sent"
  },
  {
    "id": "pr-0023",
    "seqNo": 23,
    "salesOfficer": "DP",
    "companyName": "Acqua float",
    "country": "United Kingdom",
    "followUpDuration": "",
    "estTeus": 1,
    "estTurnover": 4,
    "conversionRate": 0.1,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "FLOATING ISLAND PRICES SUBMITTED and logs prices sent after two weeks nit no response from customer. we are putting reminders"
  },
  {
    "id": "pr-0024",
    "seqNo": 24,
    "salesOfficer": "HR",
    "companyName": "Whites G",
    "country": "Australia",
    "followUpDuration": "",
    "estTeus": 12.25,
    "estTurnover": 10,
    "conversionRate": 0.5,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Prices offered but customer said he offered the price but no positive feedback from the end buyer"
  },
  {
    "id": "pr-0025",
    "seqNo": 25,
    "salesOfficer": "HR",
    "companyName": "Walmart Inc.",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 11.75,
    "estTurnover": 8,
    "conversionRate": 0.3,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "Established contact point and they have directed to anuther buying team"
  },
  {
    "id": "pr-0026",
    "seqNo": 26,
    "salesOfficer": "PD",
    "companyName": "Essenz",
    "country": "Spain",
    "followUpDuration": "",
    "estTeus": 6.75,
    "estTurnover": 8,
    "conversionRate": 0.4,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "customer visited the factory and prices offered , currenly followingup"
  },
  {
    "id": "pr-0027",
    "seqNo": 27,
    "salesOfficer": "PD",
    "companyName": "Sende",
    "country": "Latvia",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.5,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "Samples submitted. Awaiting feedback, customer sent refernces samle to us on 21st may, due to receve on 18th June 2026, GOT SAMPLES AND NEED TO REVIEW "
  },
  {
    "id": "pr-0028",
    "seqNo": 28,
    "salesOfficer": "PD",
    "companyName": "Bozam",
    "country": "Poland",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 3,
    "conversionRate": 0.5,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "customer has responded for intial samples and working on counter samples"
  },
  {
    "id": "pr-0029",
    "seqNo": 29,
    "salesOfficer": "MM",
    "companyName": "Placek",
    "country": "Czech Republic",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 3,
    "conversionRate": 0.4,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "emails send-Inquiy recoived  yet the vgm prices pending, asked more specifications about vgm pet bedding but customer is not responding"
  },
  {
    "id": "pr-0030",
    "seqNo": 30,
    "salesOfficer": "MM",
    "companyName": "Wakeun",
    "country": "Germany",
    "followUpDuration": "",
    "estTeus": 4,
    "estTurnover": 5,
    "conversionRate": 0.5,
    "expectedClosingTimeline": "6-12 Months",
    "priority": "MEDIUM",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "NEW INQUIRY SHOULD WORK COMBINED OFFER"
  },
  {
    "id": "pr-0031",
    "seqNo": 31,
    "salesOfficer": "DP",
    "companyName": "Kurkfabriek Van Avermaet",
    "country": "Belgium",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2.5,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "Samples sent, Feedback Pending"
  },
  {
    "id": "pr-0032",
    "seqNo": 32,
    "salesOfficer": "HR",
    "companyName": "Classic Home Garden",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2.5,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": ""
  },
  {
    "id": "pr-0033",
    "seqNo": 33,
    "salesOfficer": "HR",
    "companyName": "Agro De Arend",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2.5,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": ""
  },
  {
    "id": "pr-0034",
    "seqNo": 34,
    "salesOfficer": "MM",
    "companyName": "Fjeld Hagebruk",
    "country": "Norway",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 3,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "New inquiry reiceved for coco pots. Big company.  Forwarded to Manura to folowup, currenly customer is happy with his exsiting cuspplier but have the opportunity open, we are continiousely keeping in touch"
  },
  {
    "id": "pr-0035",
    "seqNo": 35,
    "salesOfficer": "MM",
    "companyName": "Et2c",
    "country": "United Kingdom",
    "followUpDuration": "",
    "estTeus": 20,
    "estTurnover": 10,
    "conversionRate": 0.5,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "New inquiry received from global sourcing office sent prices. Customer said that an indian supplier has given better prices and will consider us for next season."
  },
  {
    "id": "pr-0036",
    "seqNo": 36,
    "salesOfficer": "MM",
    "companyName": "Home Base -Jysk",
    "country": "Armania/denmark",
    "followUpDuration": "",
    "estTeus": 10.25,
    "estTurnover": 10,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Brit is the  Sourcing director,  responded and inquired about full mettress, shared the mattress  catalogue, customer said there is a  spcific  mattress JYSK buys and its not within Hayleys calalogue. Follwing up with Brit to develop as per their standard, need to get their spec."
  },
  {
    "id": "pr-0037",
    "seqNo": 37,
    "salesOfficer": "MM",
    "companyName": "Mitre10",
    "country": "Australia",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 3.7,
    "conversionRate": 0.5,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "spoke and got john's email whom is NZ soucing DIRECTOR, sent linedin too, spoke to Scott who is from Joans team who is looking at Purchasing side. initially wanted our Coco peat prices and SL prices were out then offered indian prices but unfortunately that was also out, we wanted to inquire Toyo products but at the moment they are not interested to shift buyers for Toyo products, continously follwing up."
  },
  {
    "id": "pr-0038",
    "seqNo": 38,
    "salesOfficer": "MM",
    "companyName": "Tapex Industrial",
    "country": "Australia",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 3.7,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Spoke to Callum who is starategic manager,  also sent emails to callums team mates , he said they do not have a requirment at the moment "
  },
  {
    "id": "pr-0039",
    "seqNo": 39,
    "salesOfficer": "MM",
    "companyName": "Trioau",
    "country": "Australia",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 3.7,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "emails sent , tiran is a sri lankan, connected to another sri lankan, thanuja and connected via whatzapp, said they are ok with current suppliers. Menatime shared our calalogue and Thanuja said they will come back when there is a requirement."
  },
  {
    "id": "pr-0040",
    "seqNo": 40,
    "salesOfficer": "MM",
    "companyName": "Ralista",
    "country": "Bulgaria",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2.5,
    "conversionRate": 0.3,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "PRICES OFFERED SAMPLES  sent, customer is not ready to start trial at the moment since their initial idea was copied by someone in their country."
  },
  {
    "id": "pr-0041",
    "seqNo": 41,
    "salesOfficer": "MM",
    "companyName": "Elmar",
    "country": "Belgium",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 9,
    "conversionRate": 0.3,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "Email sent-lkdin connection req rebbeca zofia product manager , returned emails, called and aksed to sent to info. Tobias is thr woner who is in  touch so said they will be back next week, also said he will connect his son due to language issue. Yet to recive a reply from him. FINALLY SAID NOT IN 2026"
  },
  {
    "id": "pr-0042",
    "seqNo": 42,
    "salesOfficer": "MM",
    "companyName": "Harster",
    "country": "Canada",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "Prices offered samples sent. happy with sampels and prices , customer is not ready to place order soon due to current situation in the market "
  },
  {
    "id": "pr-0043",
    "seqNo": 43,
    "salesOfficer": "MM",
    "companyName": "Bano Lo",
    "country": "Italy",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "spoke and sent to francesco, wanted coco peat prices initially and yet to received prices from Khashnika, NO UPDATED FROM THAT, THEY BUY FROM trump coir "
  },
  {
    "id": "pr-0044",
    "seqNo": 44,
    "salesOfficer": "MM",
    "companyName": "Nuova",
    "country": "Italy",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "called and initially asked 5kg blovck prices  ,yet to recoved prices from Khashunika"
  },
  {
    "id": "pr-0045",
    "seqNo": 45,
    "salesOfficer": "MM",
    "companyName": "Baldiflex",
    "country": "Italy",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "wrote, got response and siad they will get back after reviewing"
  },
  {
    "id": "pr-0046",
    "seqNo": 46,
    "salesOfficer": "MM",
    "companyName": "Europ",
    "country": "Netherlands",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "called and connected with sourcing manager zimon, asked about EUDR report and sent , no reply after that , continuousely follwing up"
  },
  {
    "id": "pr-0047",
    "seqNo": 47,
    "salesOfficer": "MM",
    "companyName": "4iq",
    "country": "Poland",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "emails sent to joanna,2/5/2026 ( he repied and said he will forward to purchasing, contacted again but no reply, continoosely following up with him to get the direct purchase number "
  },
  {
    "id": "pr-0048",
    "seqNo": 48,
    "salesOfficer": "MM",
    "companyName": "Ageon",
    "country": "Spain",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "sent emails , added mauro , wanted coco peat prices first, but our price was out, said they will get back when ther is inquiry for toyo items."
  },
  {
    "id": "pr-0049",
    "seqNo": 49,
    "salesOfficer": "MM",
    "companyName": "Kabloom Ltd.",
    "country": "United Kingdom",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "Emails sent no LinkedIn, inquired about coir disc, but customer yet to confirm the sizes, following up weekly."
  },
  {
    "id": "pr-0050",
    "seqNo": 50,
    "salesOfficer": "MM",
    "companyName": "Ecoiri",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "emails sent  no linkedin, whatzxaap called connected , wanrted coco peat prices initially but our price was out. They said they will get back when there is request for Toyo products "
  },
  {
    "id": "pr-0051",
    "seqNo": 51,
    "salesOfficer": "MM",
    "companyName": "Panacea",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 15,
    "estTurnover": 15,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "emails sent  no linkedin, Called and No response, Second attemt- cmnected with dyane and said they are happy with current buiyer, dyane williams , malcom , mark dennis,kate,(614) 429-6320--working  asked to call (614) 850-7000, dennis replied and said they Are happy with the current supplieer.,\"malcolm.andrews@panaceaproducts.co.uk\" <malcolm.andrews@panaceaproducts.co.uk> Md, we need to share improved prices list to impress , pending with finance. but currently buying from vietnam"
  },
  {
    "id": "pr-0052",
    "seqNo": 52,
    "salesOfficer": "MM",
    "companyName": "Dripdepot",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "forwarded to productement team, wating for the update, need to follwup up next week "
  },
  {
    "id": "pr-0053",
    "seqNo": 53,
    "salesOfficer": "MM",
    "companyName": "Brandon",
    "country": "Italy",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "customer is ok for price, samples under the process,  sample delivery chareg is high and he is not ready tom pay so need to arrange air mail"
  },
  {
    "id": "pr-0054",
    "seqNo": 54,
    "salesOfficer": "MM",
    "companyName": "Pettigardens",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "connected via linkedin sent catalogue , need to work on prices-will send improved prices from finance."
  },
  {
    "id": "pr-0055",
    "seqNo": 55,
    "salesOfficer": "MM",
    "companyName": "Nestkin",
    "country": "United Kingdom",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Connected via linked in , sent the calalogue, need to work on improved prices "
  },
  {
    "id": "pr-0056",
    "seqNo": 56,
    "salesOfficer": "MM",
    "companyName": "IWTCARGO",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 4,
    "estTurnover": 5,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "Inquiry for De watering bag and need to shsre with Richard frog"
  },
  {
    "id": "pr-0057",
    "seqNo": 57,
    "salesOfficer": "MM",
    "companyName": "Oneclarion",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "prices offered for 800nc no latex and 300gsm rc with laminated sticker, need to send samples, pending and followup with factory. customer asked to wait for sampe"
  },
  {
    "id": "pr-0058",
    "seqNo": 58,
    "salesOfficer": "MM",
    "companyName": "Greenroofsdirect",
    "country": "United Kingdom",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "Inquired aboit floating island ,RC pads, but ciustomer is also not aware about product , we sent the product information so he is yet to confirm the requirment, send few reminders, asked Malintha for update"
  },
  {
    "id": "pr-0059",
    "seqNo": 59,
    "salesOfficer": "MM",
    "companyName": "Full Service",
    "country": "Italy",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "samples prices sent, fredrico is not responding but sent sample to office, he  will reicve by next week"
  },
  {
    "id": "pr-0060",
    "seqNo": 60,
    "salesOfficer": "MM",
    "companyName": "Bmpsupplies",
    "country": "Canada",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "sent prices, followued up with Malintha if we have an positive indication, yet to get the confirmation"
  },
  {
    "id": "pr-0061",
    "seqNo": 61,
    "salesOfficer": "MM",
    "companyName": "Hanes Companies",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Sent two offeres, only 500 pcs wirebasket LCL price pending as Procurement to share the local clerance charges, sent multiple followups, calles emails, yet to recoved."
  },
  {
    "id": "pr-0062",
    "seqNo": 62,
    "salesOfficer": "MM",
    "companyName": "Beckag",
    "country": "Switzerland",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "sent two followup emails after our team physical meetup, no response yet "
  },
  {
    "id": "pr-0063",
    "seqNo": 63,
    "salesOfficer": "MM",
    "companyName": "Allinon Trade",
    "country": "Australia",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "sent offers but again utilization issue, we only can load 18000 with compressed loading for 20mft, indian supplyer can load 37500 pcs, asked to send GSM , sent prices for weed mats again and need to follup"
  },
  {
    "id": "pr-0064",
    "seqNo": 64,
    "salesOfficer": "MM",
    "companyName": "Dollar general",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 15,
    "estTurnover": 15,
    "conversionRate": 0.3,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "Need to send supplier onboarding doc"
  },
  {
    "id": "pr-0065",
    "seqNo": 65,
    "salesOfficer": "PD",
    "companyName": "Enkev",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 2,
    "estTurnover": 3,
    "conversionRate": 0.4,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Price offers send and re engineered for customer sample, awating for the response "
  },
  {
    "id": "pr-0066",
    "seqNo": 66,
    "salesOfficer": "PD",
    "companyName": "Getha",
    "country": "Malaysia",
    "followUpDuration": "",
    "estTeus": 1,
    "estTurnover": 3,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "FR Samples sent to customer for testing  BS5882-failed, Prices not approved.  NOrmal RC Trial LCL (0.1% TEU) placed for shipment (Mid Jun 26)"
  },
  {
    "id": "pr-0067",
    "seqNo": 67,
    "salesOfficer": "PD",
    "companyName": "Chillthedog",
    "country": "Germany",
    "followUpDuration": "",
    "estTeus": 1,
    "estTurnover": 4,
    "conversionRate": 0.3,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Samples and quotation submitted.  Prices not approved."
  },
  {
    "id": "pr-0068",
    "seqNo": 68,
    "salesOfficer": "MM",
    "companyName": "Grower Direct",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 6.25,
    "estTurnover": 5,
    "conversionRate": 0.3,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Prices offered for pots and issued with mold development cost. need to folloup"
  },
  {
    "id": "pr-0069",
    "seqNo": 69,
    "salesOfficer": "MM",
    "companyName": "LUCKY REPTILE GETRAUD",
    "country": "Germany",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.3,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "I have called this customer. They but 1 container / year a combined container of pots and growing media items. We requested but never got GM prices from the team unfortunately. So, we lost this opportunity."
  },
  {
    "id": "pr-0070",
    "seqNo": 70,
    "salesOfficer": "DP",
    "companyName": "Coir culture",
    "country": "Canada",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 3,
    "conversionRate": 0.1,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "supplier registration done, prices offerd for VGM products , in discssions since 2025"
  },
  {
    "id": "pr-0071",
    "seqNo": 71,
    "salesOfficer": "DP",
    "companyName": "LIKEWISE MATTING",
    "country": "United Kingdom",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.05,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Leading UK floor covering business. Few issues are with Rileys as they are having some exclusive agreements with Mr. Mendis for UK Market for ROD Mats. Prices offered for rileys PVC range as initial inquiry recived for Mats"
  },
  {
    "id": "pr-0072",
    "seqNo": 72,
    "salesOfficer": "DP",
    "companyName": "BBT -Beatle",
    "country": "Belgium",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 4,
    "conversionRate": 0.1,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "Requested details for available spec, need to provide complete infomation"
  },
  {
    "id": "pr-0073",
    "seqNo": 73,
    "salesOfficer": "HR",
    "companyName": "MDE Machinebouw",
    "country": "Netherlands",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 3,
    "conversionRate": 0.4,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Spoke to customer, waiting for their size approval to proceed samples."
  },
  {
    "id": "pr-0074",
    "seqNo": 74,
    "salesOfficer": "HR",
    "companyName": "Szkolka Pinaczy",
    "country": "Poland",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 3,
    "conversionRate": 0.4,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": ""
  },
  {
    "id": "pr-0075",
    "seqNo": 75,
    "salesOfficer": "HR",
    "companyName": "Anne Waalewijn",
    "country": "Netherlands",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 3,
    "conversionRate": 0.4,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": ""
  },
  {
    "id": "pr-0076",
    "seqNo": 76,
    "salesOfficer": "MM",
    "companyName": "Profile products",
    "country": "Canada",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "emails sent, recived inquiry for coir 5kg blocks but vgm offers not attractive and they lost interest"
  },
  {
    "id": "pr-0077",
    "seqNo": 77,
    "salesOfficer": "MM",
    "companyName": "IWTCARGO",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 4,
    "estTurnover": 5,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "Inquiry for De watering bag and need to shsre with Richard frog"
  },
  {
    "id": "pr-0078",
    "seqNo": 78,
    "salesOfficer": "MM",
    "companyName": "JARDIN Y NATURA, OUTDOOR & GARDEN",
    "country": "Spain",
    "followUpDuration": "",
    "estTeus": 4,
    "estTurnover": 5,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "emails sent , linked in conneced wth pedro, pedro shared purchases \"cmarquez@jardinynatura.com\""
  },
  {
    "id": "pr-0079",
    "seqNo": 79,
    "salesOfficer": "MM",
    "companyName": "B & G DECOR LLC",
    "country": "United Kingdom",
    "followUpDuration": "",
    "estTeus": 8,
    "estTurnover": 6,
    "conversionRate": 0.3,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "emails sent  no linkedin, EMAIL BOUCE NO CONTACT, offered via woodloge -Rob "
  },
  {
    "id": "pr-0080",
    "seqNo": 80,
    "salesOfficer": "MM",
    "companyName": "All stake su",
    "country": "Australia",
    "followUpDuration": "",
    "estTeus": 4,
    "estTurnover": 5,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "contacted sl person ad got an email of hassan purchasing manager and sent email "
  },
  {
    "id": "pr-0081",
    "seqNo": 81,
    "salesOfficer": "MM",
    "companyName": "Montreal Greenhouse",
    "country": "Canada",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "emails sent, recived inquiry poles and seems like prices are out but continoiusely following up"
  },
  {
    "id": "pr-0082",
    "seqNo": 82,
    "salesOfficer": "MM",
    "companyName": "Naturo swi",
    "country": "Switzerland",
    "followUpDuration": "",
    "estTeus": 4,
    "estTurnover": 5,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "Inquiry received for board sample, visited factory"
  },
  {
    "id": "pr-0083",
    "seqNo": 83,
    "salesOfficer": "MM",
    "companyName": "Meyer",
    "country": "Germany",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "emailed and connecteed with purchase head, not they don’t have requorment"
  },
  {
    "id": "pr-0084",
    "seqNo": 84,
    "salesOfficer": "MM",
    "companyName": "Mr Fother",
    "country": "Australia",
    "followUpDuration": "",
    "estTeus": 4,
    "estTurnover": 5,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "initially inqured for coir disc from vgm and price is out"
  },
  {
    "id": "pr-0085",
    "seqNo": 85,
    "salesOfficer": "MM",
    "companyName": "Port Cities Ltd.",
    "country": "Singapore",
    "followUpDuration": "",
    "estTeus": 1,
    "estTurnover": 1,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "currently working on the sample"
  },
  {
    "id": "pr-0086",
    "seqNo": 86,
    "salesOfficer": "PD",
    "companyName": "Spring tech dubai",
    "country": "Dubai",
    "followUpDuration": "",
    "estTeus": 6.75,
    "estTurnover": 4,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "customer said he will get back during next year"
  },
  {
    "id": "pr-0087",
    "seqNo": 87,
    "salesOfficer": "MM",
    "companyName": "Tanaka",
    "country": "Japan",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.4,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Working on the samples, quotation sent inquiry from bonterra"
  },
  {
    "id": "pr-0088",
    "seqNo": 88,
    "salesOfficer": "MM",
    "companyName": "Par gl",
    "country": "United States",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": false,
    "status": "Inquiry from bonterra ROOT MAT, PRICES OFFERED"
  },
  {
    "id": "pr-0089",
    "seqNo": 89,
    "salesOfficer": "MM",
    "companyName": "Heveya",
    "country": "Singapore",
    "followUpDuration": "",
    "estTeus": 2.25,
    "estTurnover": 2,
    "conversionRate": 0.2,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": false,
    "sampleDelivered": false,
    "status": "bedding inquiry need dispath address to send samples"
  },
  {
    "id": "pr-0090",
    "seqNo": 90,
    "salesOfficer": "MM",
    "companyName": "Backfibre",
    "country": "Local",
    "followUpDuration": "",
    "estTeus": 4.5,
    "estTurnover": 4,
    "conversionRate": 40,
    "expectedClosingTimeline": ">12 Months",
    "priority": "LOW",
    "priceOffered": true,
    "sampleDelivered": true,
    "status": "customer is also working to get leads from their buyers "
  }
];
export default prospectPipelineBaseline;
